From python:3.7

COPY . /app
WORKDIR /app

RUN apt update
RUN apt install nano
#RUN apt install vim

RUN pip3 install -r requirement.txt

RUN export AIRFLOW_HOME=~/airflow

# install from pypi using pip
RUN pip install apache-airflow

# initialize the database
RUN airflow initdb

EXPOSE 8080

# start the web server, default port is 8080
CMD airflow webserver -p 8080 & airflow scheduler

