version: '3.7'
services:
  RabbitMQ:
    image: rabbitmq:management
    ports: 
      - 5672:5672
      - 15672:15672
    environment: 
      - RABBITMQ_DEFAULT_USER=airflow
      - RABBITMQ_DEFAULT_PASS=12345678
      - RABBITMQ_DEFAULT_VHOST=airflow
    deploy:
      replicas: 1  # 從這個image開5個instance
      placement:
        constraints: [node.labels.service_type==master]

  postgres_adminer:
    image: adminer
    deploy:
      replicas: 1  # 從這個image開5個instance
    ports:
      - 8080:8080
  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: airflow
      POSTGRES_DB: airflow
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /mnt/airflow_ws/data:/var/lib/postgresql/data      
      
    ports:
      - 5432:5432
    deploy:
      replicas: 1  # 從這個image開5個instance
      placement:
        constraints: [node.labels.service_type==master]
  flower:
    image: dennis5943/airflow:2.0.1.1
    deploy:
      replicas: 1  # 從這個image開5個instance
    volumes:
      - /mnt/airflow_ws/airflow.cfg:/root/airflow/airflow.cfg
    ports:
      - '5555:5555'
    command: airflow celery flower
  worker:
    image: dennis5943/airflow:2.0.1.1
    deploy:
      replicas: 1  # 從這個image開5個instance
      placement:
        constraints: [node.labels.service_type==worker]
    volumes:
      - /mnt/airflow_ws/airflow.cfg:/root/airflow/airflow.cfg
      - /mnt/airflow_ws/dags:/root/airflow/dags
    command: airflow celery worker
  scheduler:
    image: dennis5943/airflow:2.0.1.1
    deploy:
      replicas: 1  # 從這個image開5個instance
      placement:
        constraints: [node.labels.service_type==master]
    volumes:
      - /mnt/airflow_ws/airflow.cfg:/root/airflow/airflow.cfg
      - /mnt/airflow_ws/dags:/root/airflow/dags
    command: bash -c "
          bash db_init.sh
          && airflow scheduler"
  web:
    image: dennis5943/airflow:2.0.1.1
    deploy:
      replicas: 1  # 從這個image開5個instance
      placement:
        constraints: [node.labels.service_type==master]
    volumes:
      - /mnt/airflow_ws/airflow.cfg:/root/airflow/airflow.cfg
      - /mnt/airflow_ws/dags:/root/airflow/dags
    ports:
      - '8989:8080'
    command: airflow webserver

#佈署
#docker stack deploy -c docker-compose.yml airflow_cluster

#移除佈署
#docker stack rm airflow_cluster