version: '3.7'
services:
  flower:
    image: airflow
    deploy:
      replicas: 1  # 從這個image開5個instance
      placement:
        constraints: [node.labels.pi4==true]
    volumes:
      - ./workspace/airflow.cfg:/root/airflow/airflow.cfg
      - ./workspace/resetdb.sh:/app/restdb.sh
    ports:
      - '5555:5555'
    command: airflow celery flower
  worker:
    image: airflow
    deploy:
      replicas: 1  # 從這個image開5個instance
      placement:
        constraints: [node.labels.pi4==true]
    volumes:
      - ./workspace/airflow.cfg:/root/airflow/airflow.cfg
    command: airflow celery worker
  scheduler:
    image: airflow
    deploy:
      replicas: 1  # 從這個image開5個instance
      placement:
        constraints: [node.labels.pi4==true]
    volumes:
      - ./workspace/airflow.cfg:/root/airflow/airflow.cfg
    command: airflow scheduler
  web:
    image: airflow
    deploy:
      replicas: 1  # 從這個image開5個instance
      placement:
        constraints: [node.labels.pi4==true]
    volumes:
      - ./workspace/airflow.cfg:/root/airflow/airflow.cfg
    ports:
      - '8989:8080'
    command: airflow webserver

#部署
#docker stack deploy -c docker-compose.yml airflow_cluster

#重新產生資料表
#bash restdb.sh
#airflow flower